#8004标识注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004

#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      #多个zookeeper用逗号分隔
      connect-string: 127.0.0.1:2181

